<?php //title ?>
<section class="register">
	<h2>Register</h2>
<?php if($this->error): ?>
	<p class="error">Lỗi</p>
<?php endif ?>
<?php
	$form=$this->form;
	$form->prepare();
	$form->setAttribute('action',$this->url(NULL,array('controller'=>'Register','action'=>'process')));
	$form->setAttribute('method','post');
	echo $this->form()->opentag($form);
?>
<dl class="zendform">
	<dt><?php echo $this->formLabel($form->get('name')); ?></dt>
	<dd>
		<?php
			echo $this->formElement($form->get('name'));
			echo $this->formElementErrors($form->get('name'));
		?>
	</dd>
</dl>
<?php echo $this->form()->closeTag(); ?>
</section>