 <?php
 $title = 'Users';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('users', array('action'=>'add'));?>">Add new users</a>
 </p>
 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->name);?></td>
     <td><?php echo $this->escapeHtml($user->email);?></td>
     <td>
         <td>
            <a href="<?php echo $this->url('users',
                array('action'=>'edit', 'id' => $users->id));?>">Edit</a>
            <a href="<?php echo $this->url('users',
                array('action'=>'delete', 'id' => $users->id));?>">Delete</a>
        </td>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>